/*
    Generated by Atomist on 30 06 2016 
*/
package com.jackie.service;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RestMicroserviceApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestMicroserviceApplication.class, args);
    }
}
